// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: partners.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartnerState int32

const (
	PartnerState_PARTNER_STATE_UNKNOWN PartnerState = 0
	// A connection request is/will be sent or has been sent to the parnter
	PartnerState_PARTNER_STATE_SENT PartnerState = 1
	// A connection request has been received from the partner
	PartnerState_PARTNER_STATE_RECEIVED PartnerState = 2
	// There is an active connection with that partner
	PartnerState_PARTNER_STATE_CONNECTED PartnerState = 3
	// This partner has been explicitely disconnected by the partner or by the sandbox
	PartnerState_PARTNER_STATE_DISCONNECTED PartnerState = 4
	// This partner has rejected the sandbox connection request or the sandbox has rejected the partner
	PartnerState_PARTNER_STATE_REJECTED PartnerState = 5
	// Some action couldn't be properly completed with the partner. error_msg should give more details.
	PartnerState_PARTNER_STATE_ERROR PartnerState = 6
)

// Enum value maps for PartnerState.
var (
	PartnerState_name = map[int32]string{
		0: "PARTNER_STATE_UNKNOWN",
		1: "PARTNER_STATE_SENT",
		2: "PARTNER_STATE_RECEIVED",
		3: "PARTNER_STATE_CONNECTED",
		4: "PARTNER_STATE_DISCONNECTED",
		5: "PARTNER_STATE_REJECTED",
		6: "PARTNER_STATE_ERROR",
	}
	PartnerState_value = map[string]int32{
		"PARTNER_STATE_UNKNOWN":      0,
		"PARTNER_STATE_SENT":         1,
		"PARTNER_STATE_RECEIVED":     2,
		"PARTNER_STATE_CONNECTED":    3,
		"PARTNER_STATE_DISCONNECTED": 4,
		"PARTNER_STATE_REJECTED":     5,
		"PARTNER_STATE_ERROR":        6,
	}
)

func (x PartnerState) Enum() *PartnerState {
	p := new(PartnerState)
	*p = x
	return p
}

func (x PartnerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartnerState) Descriptor() protoreflect.EnumDescriptor {
	return file_partners_proto_enumTypes[0].Descriptor()
}

func (PartnerState) Type() protoreflect.EnumType {
	return &file_partners_proto_enumTypes[0]
}

func (x PartnerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartnerState.Descriptor instead.
func (PartnerState) EnumDescriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{0}
}

type PartnerKind int32

const (
	PartnerKind_PARTNER_KIND_UNKNOWN  PartnerKind = 0
	PartnerKind_PARTNER_KIND_INTERNAL PartnerKind = 1
	PartnerKind_PARTNER_KIND_EXTERNAL PartnerKind = 2
)

// Enum value maps for PartnerKind.
var (
	PartnerKind_name = map[int32]string{
		0: "PARTNER_KIND_UNKNOWN",
		1: "PARTNER_KIND_INTERNAL",
		2: "PARTNER_KIND_EXTERNAL",
	}
	PartnerKind_value = map[string]int32{
		"PARTNER_KIND_UNKNOWN":  0,
		"PARTNER_KIND_INTERNAL": 1,
		"PARTNER_KIND_EXTERNAL": 2,
	}
)

func (x PartnerKind) Enum() *PartnerKind {
	p := new(PartnerKind)
	*p = x
	return p
}

func (x PartnerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartnerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_partners_proto_enumTypes[1].Descriptor()
}

func (PartnerKind) Type() protoreflect.EnumType {
	return &file_partners_proto_enumTypes[1]
}

func (x PartnerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartnerKind.Descriptor instead.
func (PartnerKind) EnumDescriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{1}
}

// Partners can authenticate themselves either through hostname (sandbox) or public key
type PublicKeyAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *PublicKeyAuthentication) Reset() {
	*x = PublicKeyAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKeyAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyAuthentication) ProtoMessage() {}

func (x *PublicKeyAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyAuthentication.ProtoReflect.Descriptor instead.
func (*PublicKeyAuthentication) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeyAuthentication) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type HostnameAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *HostnameAuthentication) Reset() {
	*x = HostnameAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostnameAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostnameAuthentication) ProtoMessage() {}

func (x *HostnameAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostnameAuthentication.ProtoReflect.Descriptor instead.
func (*HostnameAuthentication) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{1}
}

func (x *HostnameAuthentication) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// A partner is an external sandbox with which it is possible to match audiences
type Partner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The hostname of the partner sandbox is the canonical identifier to authenticate
	//
	// Deprecated: Do not use.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The icon to represent the partner in the UI
	IconUrl string `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// A custom URL to use in order to initiate communication with the partner
	Url   string       `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	State PartnerState `protobuf:"varint,6,opt,name=state,proto3,enum=v1.PartnerState" json:"state,omitempty"`
	// Optional error message associate with the ERROR state
	ErrorMsg  string                 `protobuf:"bytes,7,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Slug for a partner, for authentication purposes
	Slug string `protobuf:"bytes,10,opt,name=slug,proto3" json:"slug,omitempty"`
	// Partner's way to authenticate themselves
	//
	// Types that are assignable to AuthenticationAttrs:
	//	*Partner_PublicKeyAuth
	//	*Partner_HostnameAuth
	AuthenticationAttrs isPartner_AuthenticationAttrs `protobuf_oneof:"authentication_attrs"`
	Kind                PartnerKind                   `protobuf:"varint,13,opt,name=kind,proto3,enum=v1.PartnerKind" json:"kind,omitempty"`
}

func (x *Partner) Reset() {
	*x = Partner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partner) ProtoMessage() {}

func (x *Partner) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partner.ProtoReflect.Descriptor instead.
func (*Partner) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{2}
}

func (x *Partner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Partner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Do not use.
func (x *Partner) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Partner) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Partner) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Partner) GetState() PartnerState {
	if x != nil {
		return x.State
	}
	return PartnerState_PARTNER_STATE_UNKNOWN
}

func (x *Partner) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *Partner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Partner) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Partner) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (m *Partner) GetAuthenticationAttrs() isPartner_AuthenticationAttrs {
	if m != nil {
		return m.AuthenticationAttrs
	}
	return nil
}

func (x *Partner) GetPublicKeyAuth() *PublicKeyAuthentication {
	if x, ok := x.GetAuthenticationAttrs().(*Partner_PublicKeyAuth); ok {
		return x.PublicKeyAuth
	}
	return nil
}

func (x *Partner) GetHostnameAuth() *HostnameAuthentication {
	if x, ok := x.GetAuthenticationAttrs().(*Partner_HostnameAuth); ok {
		return x.HostnameAuth
	}
	return nil
}

func (x *Partner) GetKind() PartnerKind {
	if x != nil {
		return x.Kind
	}
	return PartnerKind_PARTNER_KIND_UNKNOWN
}

type isPartner_AuthenticationAttrs interface {
	isPartner_AuthenticationAttrs()
}

type Partner_PublicKeyAuth struct {
	PublicKeyAuth *PublicKeyAuthentication `protobuf:"bytes,11,opt,name=public_key_auth,json=publicKeyAuth,proto3,oneof"`
}

type Partner_HostnameAuth struct {
	HostnameAuth *HostnameAuthentication `protobuf:"bytes,12,opt,name=hostname_auth,json=hostnameAuth,proto3,oneof"`
}

func (*Partner_PublicKeyAuth) isPartner_AuthenticationAttrs() {}

func (*Partner_HostnameAuth) isPartner_AuthenticationAttrs() {}

type LookupPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpOrigin string `protobuf:"bytes,1,opt,name=http_origin,json=httpOrigin,proto3" json:"http_origin,omitempty"`
}

func (x *LookupPartnerReq) Reset() {
	*x = LookupPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPartnerReq) ProtoMessage() {}

func (x *LookupPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPartnerReq.ProtoReflect.Descriptor instead.
func (*LookupPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{3}
}

func (x *LookupPartnerReq) GetHttpOrigin() string {
	if x != nil {
		return x.HttpOrigin
	}
	return ""
}

type LookupPartnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *ExternalInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *LookupPartnerRes) Reset() {
	*x = LookupPartnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupPartnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPartnerRes) ProtoMessage() {}

func (x *LookupPartnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPartnerRes.ProtoReflect.Descriptor instead.
func (*LookupPartnerRes) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{4}
}

func (x *LookupPartnerRes) GetInfo() *ExternalInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ConnectPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IconUrl  string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Url      string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ConnectPartnerReq) Reset() {
	*x = ConnectPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPartnerReq) ProtoMessage() {}

func (x *ConnectPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPartnerReq.ProtoReflect.Descriptor instead.
func (*ConnectPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectPartnerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectPartnerReq) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ConnectPartnerReq) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ConnectPartnerReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ConnectPartnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partner *Partner `protobuf:"bytes,1,opt,name=partner,proto3" json:"partner,omitempty"`
}

func (x *ConnectPartnerRes) Reset() {
	*x = ConnectPartnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectPartnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPartnerRes) ProtoMessage() {}

func (x *ConnectPartnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPartnerRes.ProtoReflect.Descriptor instead.
func (*ConnectPartnerRes) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectPartnerRes) GetPartner() *Partner {
	if x != nil {
		return x.Partner
	}
	return nil
}

type ApprovePartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ApprovePartnerReq) Reset() {
	*x = ApprovePartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApprovePartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePartnerReq) ProtoMessage() {}

func (x *ApprovePartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePartnerReq.ProtoReflect.Descriptor instead.
func (*ApprovePartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{7}
}

func (x *ApprovePartnerReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RejectPartnerReq) Reset() {
	*x = RejectPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPartnerReq) ProtoMessage() {}

func (x *RejectPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPartnerReq.ProtoReflect.Descriptor instead.
func (*RejectPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{8}
}

func (x *RejectPartnerReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DisconnectPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DisconnectPartnerReq) Reset() {
	*x = DisconnectPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectPartnerReq) ProtoMessage() {}

func (x *DisconnectPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectPartnerReq.ProtoReflect.Descriptor instead.
func (*DisconnectPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{9}
}

func (x *DisconnectPartnerReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PartnerFilters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []PartnerState `protobuf:"varint,1,rep,packed,name=states,proto3,enum=v1.PartnerState" json:"states,omitempty"`
	Kinds  []PartnerKind  `protobuf:"varint,2,rep,packed,name=kinds,proto3,enum=v1.PartnerKind" json:"kinds,omitempty"`
}

func (x *PartnerFilters) Reset() {
	*x = PartnerFilters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnerFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerFilters) ProtoMessage() {}

func (x *PartnerFilters) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerFilters.ProtoReflect.Descriptor instead.
func (*PartnerFilters) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{10}
}

func (x *PartnerFilters) GetStates() []PartnerState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *PartnerFilters) GetKinds() []PartnerKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

type ListPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *PageReq        `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters    *PartnerFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	Sorts      []*SortField    `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Search     string          `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *ListPartnerReq) Reset() {
	*x = ListPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartnerReq) ProtoMessage() {}

func (x *ListPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartnerReq.ProtoReflect.Descriptor instead.
func (*ListPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{11}
}

func (x *ListPartnerReq) GetPagination() *PageReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPartnerReq) GetFilters() *PartnerFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListPartnerReq) GetSorts() []*SortField {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *ListPartnerReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListPartnerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []*Partner `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination *PageRes   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListPartnerRes) Reset() {
	*x = ListPartnerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPartnerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartnerRes) ProtoMessage() {}

func (x *ListPartnerRes) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartnerRes.ProtoReflect.Descriptor instead.
func (*ListPartnerRes) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{12}
}

func (x *ListPartnerRes) GetData() []*Partner {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPartnerRes) GetPagination() *PageRes {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PartnersInitToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// URL to and external/api/info endpoint
	SandboxInfo string                 `protobuf:"bytes,2,opt,name=sandbox_info,json=sandboxInfo,proto3" json:"sandbox_info,omitempty"`
	Secret      string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *PartnersInitToken) Reset() {
	*x = PartnersInitToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartnersInitToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnersInitToken) ProtoMessage() {}

func (x *PartnersInitToken) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnersInitToken.ProtoReflect.Descriptor instead.
func (*PartnersInitToken) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{13}
}

func (x *PartnersInitToken) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PartnersInitToken) GetSandboxInfo() string {
	if x != nil {
		return x.SandboxInfo
	}
	return ""
}

func (x *PartnersInitToken) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *PartnersInitToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PartnersInitToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateExternalInitTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the (adhoc?) partner
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateExternalInitTokenReq) Reset() {
	*x = CreateExternalInitTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExternalInitTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalInitTokenReq) ProtoMessage() {}

func (x *CreateExternalInitTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalInitTokenReq.ProtoReflect.Descriptor instead.
func (*CreateExternalInitTokenReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{14}
}

func (x *CreateExternalInitTokenReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateExternalInitTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *PartnersInitToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateExternalInitTokenRes) Reset() {
	*x = CreateExternalInitTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExternalInitTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalInitTokenRes) ProtoMessage() {}

func (x *CreateExternalInitTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalInitTokenRes.ProtoReflect.Descriptor instead.
func (*CreateExternalInitTokenRes) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{15}
}

func (x *CreateExternalInitTokenRes) GetToken() *PartnersInitToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type RegisterExternalPartnerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterExternalPartnerReq) Reset() {
	*x = RegisterExternalPartnerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterExternalPartnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterExternalPartnerReq) ProtoMessage() {}

func (x *RegisterExternalPartnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterExternalPartnerReq.ProtoReflect.Descriptor instead.
func (*RegisterExternalPartnerReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterExternalPartnerReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterExternalPartnerReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetInitTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *GetInitTokenReq) Reset() {
	*x = GetInitTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInitTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitTokenReq) ProtoMessage() {}

func (x *GetInitTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitTokenReq.ProtoReflect.Descriptor instead.
func (*GetInitTokenReq) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{17}
}

func (x *GetInitTokenReq) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetInitTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetInitTokenRes) Reset() {
	*x = GetInitTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_partners_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInitTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInitTokenRes) ProtoMessage() {}

func (x *GetInitTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_partners_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInitTokenRes.ProtoReflect.Descriptor instead.
func (*GetInitTokenRes) Descriptor() ([]byte, []int) {
	return file_partners_proto_rawDescGZIP(), []int{18}
}

func (x *GetInitTokenRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_partners_proto protoreflect.FileDescriptor

var file_partners_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x34, 0x0a,
	0x16, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x90, 0x04, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12,
	0x45, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x75,
	0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x41, 0x75, 0x74, 0x68, 0x12, 0x41, 0x0a, 0x0d, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x16,
	0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x22, 0x33, 0x0a, 0x10, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x74,
	0x74, 0x70, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x68, 0x74, 0x74, 0x70, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x38, 0x0a, 0x10, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x70, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63,
	0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63,
	0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x07,
	0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x25, 0x0a, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64,
	0x52, 0x05, 0x6b, 0x69, 0x6e, 0x64, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x07, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x52, 0x05, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x22, 0x5e, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xd8, 0x01, 0x0a, 0x11, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x49,
	0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x30, 0x0a,
	0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49,
	0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x49, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x51, 0x0a, 0x1a, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x6c, 0x75, 0x67, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2a, 0xcf, 0x01,
	0x0a, 0x0c, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19,
	0x0a, 0x15, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x41, 0x52,
	0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1b, 0x0a,
	0x17, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x41,
	0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41,
	0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x06, 0x2a,
	0x5d, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18,
	0x0a, 0x14, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x41, 0x52, 0x54,
	0x4e, 0x45, 0x52, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x41, 0x52, 0x54, 0x4e, 0x45, 0x52, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_partners_proto_rawDescOnce sync.Once
	file_partners_proto_rawDescData = file_partners_proto_rawDesc
)

func file_partners_proto_rawDescGZIP() []byte {
	file_partners_proto_rawDescOnce.Do(func() {
		file_partners_proto_rawDescData = protoimpl.X.CompressGZIP(file_partners_proto_rawDescData)
	})
	return file_partners_proto_rawDescData
}

var file_partners_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_partners_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_partners_proto_goTypes = []interface{}{
	(PartnerState)(0),                  // 0: v1.PartnerState
	(PartnerKind)(0),                   // 1: v1.PartnerKind
	(*PublicKeyAuthentication)(nil),    // 2: v1.PublicKeyAuthentication
	(*HostnameAuthentication)(nil),     // 3: v1.HostnameAuthentication
	(*Partner)(nil),                    // 4: v1.Partner
	(*LookupPartnerReq)(nil),           // 5: v1.LookupPartnerReq
	(*LookupPartnerRes)(nil),           // 6: v1.LookupPartnerRes
	(*ConnectPartnerReq)(nil),          // 7: v1.ConnectPartnerReq
	(*ConnectPartnerRes)(nil),          // 8: v1.ConnectPartnerRes
	(*ApprovePartnerReq)(nil),          // 9: v1.ApprovePartnerReq
	(*RejectPartnerReq)(nil),           // 10: v1.RejectPartnerReq
	(*DisconnectPartnerReq)(nil),       // 11: v1.DisconnectPartnerReq
	(*PartnerFilters)(nil),             // 12: v1.PartnerFilters
	(*ListPartnerReq)(nil),             // 13: v1.ListPartnerReq
	(*ListPartnerRes)(nil),             // 14: v1.ListPartnerRes
	(*PartnersInitToken)(nil),          // 15: v1.PartnersInitToken
	(*CreateExternalInitTokenReq)(nil), // 16: v1.CreateExternalInitTokenReq
	(*CreateExternalInitTokenRes)(nil), // 17: v1.CreateExternalInitTokenRes
	(*RegisterExternalPartnerReq)(nil), // 18: v1.RegisterExternalPartnerReq
	(*GetInitTokenReq)(nil),            // 19: v1.GetInitTokenReq
	(*GetInitTokenRes)(nil),            // 20: v1.GetInitTokenRes
	(*timestamppb.Timestamp)(nil),      // 21: google.protobuf.Timestamp
	(*ExternalInfo)(nil),               // 22: v1.ExternalInfo
	(*PageReq)(nil),                    // 23: v1.PageReq
	(*SortField)(nil),                  // 24: v1.SortField
	(*PageRes)(nil),                    // 25: v1.PageRes
}
var file_partners_proto_depIdxs = []int32{
	0,  // 0: v1.Partner.state:type_name -> v1.PartnerState
	21, // 1: v1.Partner.created_at:type_name -> google.protobuf.Timestamp
	21, // 2: v1.Partner.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: v1.Partner.public_key_auth:type_name -> v1.PublicKeyAuthentication
	3,  // 4: v1.Partner.hostname_auth:type_name -> v1.HostnameAuthentication
	1,  // 5: v1.Partner.kind:type_name -> v1.PartnerKind
	22, // 6: v1.LookupPartnerRes.info:type_name -> v1.ExternalInfo
	4,  // 7: v1.ConnectPartnerRes.partner:type_name -> v1.Partner
	0,  // 8: v1.PartnerFilters.states:type_name -> v1.PartnerState
	1,  // 9: v1.PartnerFilters.kinds:type_name -> v1.PartnerKind
	23, // 10: v1.ListPartnerReq.pagination:type_name -> v1.PageReq
	12, // 11: v1.ListPartnerReq.filters:type_name -> v1.PartnerFilters
	24, // 12: v1.ListPartnerReq.sorts:type_name -> v1.SortField
	4,  // 13: v1.ListPartnerRes.data:type_name -> v1.Partner
	25, // 14: v1.ListPartnerRes.pagination:type_name -> v1.PageRes
	21, // 15: v1.PartnersInitToken.created_at:type_name -> google.protobuf.Timestamp
	21, // 16: v1.PartnersInitToken.expires_at:type_name -> google.protobuf.Timestamp
	15, // 17: v1.CreateExternalInitTokenRes.token:type_name -> v1.PartnersInitToken
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_partners_proto_init() }
func file_partners_proto_init() {
	if File_partners_proto != nil {
		return
	}
	file_common_proto_init()
	file_external_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_partners_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKeyAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostnameAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupPartnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectPartnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApprovePartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartnerFilters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPartnerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartnersInitToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExternalInitTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExternalInitTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterExternalPartnerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInitTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_partners_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInitTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_partners_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Partner_PublicKeyAuth)(nil),
		(*Partner_HostnameAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_partners_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partners_proto_goTypes,
		DependencyIndexes: file_partners_proto_depIdxs,
		EnumInfos:         file_partners_proto_enumTypes,
		MessageInfos:      file_partners_proto_msgTypes,
	}.Build()
	File_partners_proto = out.File
	file_partners_proto_rawDesc = nil
	file_partners_proto_goTypes = nil
	file_partners_proto_depIdxs = nil
}
