// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PartnersInitToken is an object representing the database table.
type PartnersInitToken struct {
	Slug        string    `boil:"slug" json:"slug" toml:"slug" yaml:"slug"`
	SandboxInfo string    `boil:"sandbox_info" json:"sandbox_info" toml:"sandbox_info" yaml:"sandbox_info"`
	Secret      string    `boil:"secret" json:"secret" toml:"secret" yaml:"secret"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt   time.Time `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`

	R *partnersInitTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L partnersInitTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PartnersInitTokenColumns = struct {
	Slug        string
	SandboxInfo string
	Secret      string
	CreatedAt   string
	ExpiresAt   string
}{
	Slug:        "slug",
	SandboxInfo: "sandbox_info",
	Secret:      "secret",
	CreatedAt:   "created_at",
	ExpiresAt:   "expires_at",
}

// Generated where

var PartnersInitTokenWhere = struct {
	Slug        whereHelperstring
	SandboxInfo whereHelperstring
	Secret      whereHelperstring
	CreatedAt   whereHelpertime_Time
	ExpiresAt   whereHelpertime_Time
}{
	Slug:        whereHelperstring{field: "\"partners_init_tokens\".\"slug\""},
	SandboxInfo: whereHelperstring{field: "\"partners_init_tokens\".\"sandbox_info\""},
	Secret:      whereHelperstring{field: "\"partners_init_tokens\".\"secret\""},
	CreatedAt:   whereHelpertime_Time{field: "\"partners_init_tokens\".\"created_at\""},
	ExpiresAt:   whereHelpertime_Time{field: "\"partners_init_tokens\".\"expires_at\""},
}

// PartnersInitTokenRels is where relationship names are stored.
var PartnersInitTokenRels = struct {
}{}

// partnersInitTokenR is where relationships are stored.
type partnersInitTokenR struct {
}

// NewStruct creates a new relationship struct
func (*partnersInitTokenR) NewStruct() *partnersInitTokenR {
	return &partnersInitTokenR{}
}

// partnersInitTokenL is where Load methods for each relationship are stored.
type partnersInitTokenL struct{}

var (
	partnersInitTokenAllColumns            = []string{"slug", "sandbox_info", "secret", "created_at", "expires_at"}
	partnersInitTokenColumnsWithoutDefault = []string{"slug", "sandbox_info", "secret", "created_at", "expires_at"}
	partnersInitTokenColumnsWithDefault    = []string{}
	partnersInitTokenPrimaryKeyColumns     = []string{"slug"}
)

type (
	// PartnersInitTokenSlice is an alias for a slice of pointers to PartnersInitToken.
	// This should generally be used opposed to []PartnersInitToken.
	PartnersInitTokenSlice []*PartnersInitToken

	partnersInitTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	partnersInitTokenType                 = reflect.TypeOf(&PartnersInitToken{})
	partnersInitTokenMapping              = queries.MakeStructMapping(partnersInitTokenType)
	partnersInitTokenPrimaryKeyMapping, _ = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, partnersInitTokenPrimaryKeyColumns)
	partnersInitTokenInsertCacheMut       sync.RWMutex
	partnersInitTokenInsertCache          = make(map[string]insertCache)
	partnersInitTokenUpdateCacheMut       sync.RWMutex
	partnersInitTokenUpdateCache          = make(map[string]updateCache)
	partnersInitTokenUpsertCacheMut       sync.RWMutex
	partnersInitTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single partnersInitToken record from the query.
func (q partnersInitTokenQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PartnersInitToken, error) {
	o := &PartnersInitToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for partners_init_tokens")
	}

	return o, nil
}

// All returns all PartnersInitToken records from the query.
func (q partnersInitTokenQuery) All(ctx context.Context, exec boil.ContextExecutor) (PartnersInitTokenSlice, error) {
	var o []*PartnersInitToken

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PartnersInitToken slice")
	}

	return o, nil
}

// Count returns the count of all PartnersInitToken records in the query.
func (q partnersInitTokenQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count partners_init_tokens rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q partnersInitTokenQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if partners_init_tokens exists")
	}

	return count > 0, nil
}

// PartnersInitTokens retrieves all the records using an executor.
func PartnersInitTokens(mods ...qm.QueryMod) partnersInitTokenQuery {
	mods = append(mods, qm.From("\"partners_init_tokens\""))
	return partnersInitTokenQuery{NewQuery(mods...)}
}

// FindPartnersInitToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPartnersInitToken(ctx context.Context, exec boil.ContextExecutor, slug string, selectCols ...string) (*PartnersInitToken, error) {
	partnersInitTokenObj := &PartnersInitToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"partners_init_tokens\" where \"slug\"=$1", sel,
	)

	q := queries.Raw(query, slug)

	err := q.Bind(ctx, exec, partnersInitTokenObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from partners_init_tokens")
	}

	return partnersInitTokenObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PartnersInitToken) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no partners_init_tokens provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(partnersInitTokenColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	partnersInitTokenInsertCacheMut.RLock()
	cache, cached := partnersInitTokenInsertCache[key]
	partnersInitTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			partnersInitTokenAllColumns,
			partnersInitTokenColumnsWithDefault,
			partnersInitTokenColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"partners_init_tokens\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"partners_init_tokens\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into partners_init_tokens")
	}

	if !cached {
		partnersInitTokenInsertCacheMut.Lock()
		partnersInitTokenInsertCache[key] = cache
		partnersInitTokenInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the PartnersInitToken.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PartnersInitToken) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	partnersInitTokenUpdateCacheMut.RLock()
	cache, cached := partnersInitTokenUpdateCache[key]
	partnersInitTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			partnersInitTokenAllColumns,
			partnersInitTokenPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update partners_init_tokens, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"partners_init_tokens\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, partnersInitTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, append(wl, partnersInitTokenPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update partners_init_tokens row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for partners_init_tokens")
	}

	if !cached {
		partnersInitTokenUpdateCacheMut.Lock()
		partnersInitTokenUpdateCache[key] = cache
		partnersInitTokenUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q partnersInitTokenQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for partners_init_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for partners_init_tokens")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PartnersInitTokenSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partnersInitTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"partners_init_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, partnersInitTokenPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in partnersInitToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all partnersInitToken")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PartnersInitToken) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no partners_init_tokens provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(partnersInitTokenColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	partnersInitTokenUpsertCacheMut.RLock()
	cache, cached := partnersInitTokenUpsertCache[key]
	partnersInitTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			partnersInitTokenAllColumns,
			partnersInitTokenColumnsWithDefault,
			partnersInitTokenColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			partnersInitTokenAllColumns,
			partnersInitTokenPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert partners_init_tokens, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(partnersInitTokenPrimaryKeyColumns))
			copy(conflict, partnersInitTokenPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"partners_init_tokens\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(partnersInitTokenType, partnersInitTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert partners_init_tokens")
	}

	if !cached {
		partnersInitTokenUpsertCacheMut.Lock()
		partnersInitTokenUpsertCache[key] = cache
		partnersInitTokenUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single PartnersInitToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PartnersInitToken) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PartnersInitToken provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), partnersInitTokenPrimaryKeyMapping)
	sql := "DELETE FROM \"partners_init_tokens\" WHERE \"slug\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from partners_init_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for partners_init_tokens")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q partnersInitTokenQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no partnersInitTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from partners_init_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for partners_init_tokens")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PartnersInitTokenSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partnersInitTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"partners_init_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, partnersInitTokenPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from partnersInitToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for partners_init_tokens")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PartnersInitToken) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPartnersInitToken(ctx, exec, o.Slug)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PartnersInitTokenSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PartnersInitTokenSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), partnersInitTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"partners_init_tokens\".* FROM \"partners_init_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, partnersInitTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PartnersInitTokenSlice")
	}

	*o = slice

	return nil
}

// PartnersInitTokenExists checks if the PartnersInitToken row exists.
func PartnersInitTokenExists(ctx context.Context, exec boil.ContextExecutor, slug string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"partners_init_tokens\" where \"slug\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, slug)
	}
	row := exec.QueryRowContext(ctx, sql, slug)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if partners_init_tokens exists")
	}

	return exists, nil
}
